
--Display the first name, last name, email, and city of every customer who lives in Chennai.
SELECT first_name,last_name,email,city FROM Customers where city='Chennai';

--Display each booking along with the customer's first name, last name, check-in date, check-out date, and booking status.
SELECT c.first_name,c.last_name,b.check_in_date,b.check_out_date,b.status FROM Customers as c JOIN Bookings as b ON c.customer_id=b.customer_id;

--Find all customers who have never made a booking.
SELECT c.first_name,c.last_name FROM Customers as c LEFT JOIN Bookings as b ON  c.customer_id = b.customer_id WHERE b.booking_id IS NULL;
--Display each booking's: customer first name,customer last name,room number,room type,base price
SELECT
    c.first_name,
    c.last_name,
    r.room_number,
    rt.room_type,
    rt.base_price
FROM Customers AS c
JOIN Bookings AS b
    ON c.customer_id = b.customer_id
JOIN Rooms AS r
    ON b.room_id = r.room_id
JOIN RoomTypes AS rt
    ON r.room_type_id = rt.room_type_id;
--For every booking, calculate the number of nights stayed.

SELECT booking_id,check_in_date,check_out_date,DATEDIFF(day,check_in_date,check_out_date) as nights FROM Bookings ;

--Calculate booking cost
SELECT b.booking_id,r.room_number,rt.base_price,DATEDIFF(day,check_in_date,check_out_date) as nights,DATEDIFF(day,check_in_date,check_out_date)* rt.base_price as total_cost FROM Bookings as B JOIN  Rooms as r ON b.room_id=r.room_id JOIN RoomTypes as rt ON r.room_type_id=rt.room_type_id;
--Find the total revenue generated by the hotel from all bookings.
SELECT SUM(DATEDIFF(day,check_in_date,check_out_date)* rt.base_price) as total_cost FROM Bookings as b JOIN  Rooms as r ON b.room_id=r.room_id JOIN RoomTypes as rt ON r.room_type_id=rt.room_type_id WHERE b.status<>'Cancelled';
--Find the total revenue generated by each room type.
SELECT rt.room_type,SUM(DATEDIFF(day,check_in_date,check_out_date)* rt.base_price) as total_cost FROM Bookings as b JOIN  Rooms as r ON b.room_id=r.room_id JOIN RoomTypes as rt ON r.room_type_id=rt.room_type_id  WHERE b.status<>'Cancelled' GROUP BY rt.room_type;
--Find the number of bookings made by each customer.
SELECT
    c.first_name,
    c.last_name,
    COUNT(b.booking_id) AS booking_count
FROM Customers AS c
LEFT JOIN Bookings AS b
    ON c.customer_id = b.customer_id
GROUP BY
    c.first_name,
    c.last_name;
--Find customers who have made more than 1 booking.
SELECT
    c.first_name,
    c.last_name,
    COUNT(b.booking_id) AS booking_count
FROM Customers AS c
LEFT JOIN Bookings AS b
    ON c.customer_id = b.customer_id
GROUP BY
    c.first_name,
    c.last_name
    HAVING COUNT(b.booking_id) > 1;

--Find the average number of nights per booking.
SELECT AVG(CAST(DATEDIFF(day,check_in_date,check_out_date)AS DECIMAL(10,2)))  as avg_nights FROM Bookings as b JOIN  Rooms as r ON b.room_id=r.room_id JOIN RoomTypes as rt ON r.room_type_id=rt.room_type_id WHERE b.status<>'Cancelled';
--Find the average number of nights stayed for each room type.
SELECT rt.room_type,AVG(CAST(DATEDIFF(day,check_in_date,check_out_date)AS DECIMAL(10,2)))  as avg_nights FROM Bookings as b JOIN  Rooms as r ON b.room_id=r.room_id JOIN RoomTypes as rt ON r.room_type_id=rt.room_type_id WHERE b.status<>'Cancelled' GROUP BY rt.room_type;
--For each room type, find: the highest base price,the lowest base price
SELECT
    room_type,
    MAX(base_price) AS highest_price,
    MIN(base_price) AS lowest_price
FROM RoomTypes
GROUP BY room_type;
